notifications:
  slack:
    rooms:
      - appliedis:uVEqM1cN6Vowz0OpaXWN7pCa#18fagilebpa
language: node_js
install:
  - cd $TRAVIS_BUILD_DIR/ui
  - npm install -g gulp bower
  - npm install
  - bower install
  - cd $TRAVIS_BUILD_DIR/server
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/ui
  - gulp test
  - gulp dist
  - cd $TRAVIS_BUILD_DIR/server
  - gulp test
  - cd $TRAVIS_BUILD_DIR
sudo: required
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kyle.linden@appliedis.com
  password:
    secure: UhZ7KxjaXe5ZIL7xs2xhIkWWylmDyPU2uVGcRO4lDbYU4rLrCpm0ubUS9NUwkbWdyzQQZwHoHv8llk0y+8KGTP1CY0c9JKEb23rd10fvWZVYcUatA1Uj+iXSUlD1DjuSv98aZgFr0wIpctUxJg9/uRSO4573YNCar2JPjHpI9vsxV8R0AcKhv0Ikq4HuV6Qn1cRQpWWrfZjlYY/+DlDcllCwxS8g3t8PIUXvm9QHqcuyQXrXPcXOLk5yhXKkiszcMibEuF0Fsscef+SJZ1TPfgggsam8zbP9ARvCHtCzjoI+RogTcAYAEAWvtGewethPvvOygnL1UR0fkmApoGpRQZ+Legu8v07FVgSjX8AvHsltCPSfnyUVp7siroVUew3ClX2ac4fhmd9egt7YDD4FUPCwQc6t8DPYY0kkNPteMOJQwEUmP9NfXieVO1tiDteA2Eg3nC4tYDjDRZwYV4UPsNLwzliBqwFWgQ+0xmsiVFXxi3WhLfOMmfsztVXeWAuKmRdIH9zhHrMj48GktEcdPFMGhybpzepgCVWe7MosupNisb6b86mRYGb47cuLISc9nmMr+p/FezRkiRezfxg1Vwhfd3jhSt0m9h9kPwySTPqjb0xSczzCOmkdnglNfBqBES9Yy3dyfyJQvvojYKGOv/GpTW65RgV+nQSnQmtoU70=
  organization: AIS
  space: development
