source 'https://rubygems.org'

gem 'rails', '7.1.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0', '>= 5.0.8'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'font-awesome-rails', '>= 4.7.0.8'

gem 'jquery-rails', '>= 4.0.5'
gem "haml-rails", "~> 2.1", ">= 2.1.0"
gem 'foundation-rails', '>= 5.5.3.1'
gem 'faraday'
gem 'json'
gem 'hashie'
gem 'kaminari', '>= 0.17.0'
gem 'chartkick'
gem "highcharts-rails", ">= 4.1.6"

group :test do
  gem 'webmock'
  gem 'i18n-tasks', '>= 0.9.17'
end

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.0'
  gem 'capybara-webkit'
  gem 'spring'
  gem 'rspec_junit_formatter'
end

