source 'https://rubygems.org'

gem 'rails', '5.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0', '>= 5.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.1'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'font-awesome-rails', '>= 4.5.0.1'

gem 'jquery-rails'
gem "haml-rails", "~> 0.9", ">= 0.9.0"
gem 'foundation-rails'
gem 'faraday'
gem 'json'
gem 'hashie'
gem 'kaminari'
gem 'chartkick'
gem "highcharts-rails"

group :test do
  gem 'webmock'
  gem 'i18n-tasks'
end

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.0'
  gem 'capybara-webkit'
  gem 'spring'
  gem 'rspec_junit_formatter'
end

