source 'https://rubygems.org'

gem 'rails', '6.1.7.3'
gem 'sqlite3'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.2.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'font-awesome-rails', '>= 4.7.0.6'

gem 'jquery-rails', '>= 4.4.0'
gem "haml-rails", "~> 1.0", ">= 1.0.0"
gem 'foundation-rails'
gem 'faraday'
gem 'json', '>= 2.3.0'
gem 'hashie'
gem 'kaminari', '>= 1.2.1'
gem 'chartkick', '>= 3.4.0'
gem "highcharts-rails"

group :test do
  gem 'webmock'
  gem 'i18n-tasks'
end

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.0'
  gem 'capybara-webkit'
  gem 'spring'
  gem 'rspec_junit_formatter'
end

